/**
 * Self-contained HTML report. One file, no external assets, no JS frameworks.
 * Renders the scorecard metrics table and an inline-SVG equity curve so it
 * opens in any browser offline. Ideal for a demo or a shared artifact.
 */

import type { Scorecard, Fill } from "../types.js";

/** Build the full HTML document as a string. */
export function renderHtml(
  scorecard: Scorecard,
  equity: readonly number[],
  fills: readonly Fill[],
): string {
  const m = scorecard.metrics;
  const man = scorecard.manifest;

  const curve = sparkline(equity, 900, 260);
  const rows = METRIC_ROWS.map(([label, value]) => value(m)).join("");
  const tradeRows = fills
    .slice(0, 200)
    .map((f) => tradeRow(f))
    .join("");

  const ret = m.totalReturnPct;
  const retClass = ret >= 0 ? "pos" : "neg";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>AgentBench scorecard — ${esc(scorecard.agent)}</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #0b0e14; color: #d7dce5;
    font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }
  .wrap { max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #8a93a6; font-size: 13px; margin-bottom: 24px; }
  .hero { display: flex; gap: 28px; align-items: baseline; margin: 18px 0 26px; flex-wrap: wrap; }
  .hero .ret { font-size: 40px; font-weight: 700; }
  .pos { color: #3fb950; } .neg { color: #f85149; }
  .card { background: #11151f; border: 1px solid #1f2632; border-radius: 10px;
    padding: 18px 20px; margin: 18px 0; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 14px 24px; }
  .metric .k { color: #8a93a6; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
  .metric .v { font-size: 18px; font-weight: 600; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: right; padding: 6px 10px; border-bottom: 1px solid #1a212c; }
  th:first-child, td:first-child { text-align: left; }
  th { color: #8a93a6; font-weight: 600; }
  .buy { color: #3fb950; } .sell { color: #f85149; }
  svg { display: block; width: 100%; height: auto; }
  .foot { color: #5b6373; font-size: 12px; margin-top: 28px; }
  code { background: #1a212c; padding: 1px 6px; border-radius: 4px; font-size: 12px; }
</style>
</head>
<body>
<div class="wrap">
  <h1>AgentBench scorecard</h1>
  <div class="sub">${esc(scorecard.agent)} · ${esc(man.symbol)} ${esc(man.granularity)} · ${man.bars} bars · seed ${man.engine.seed}</div>

  <div class="hero">
    <div>
      <div class="metric"><span class="k">Total return</span></div>
      <div class="ret ${retClass}">${fmtPct(ret)}</div>
    </div>
    <div>
      <div class="metric"><span class="k">Equity</span></div>
      <div class="ret">${fmt(m.startingEquity)} → ${fmt(m.finalEquity)}</div>
    </div>
  </div>

  <div class="card">${curve}</div>

  <div class="card">
    <div class="grid">${rows}</div>
  </div>

  <div class="card">
    <h3 style="margin:0 0 12px;font-size:15px">Trade ledger ${fills.length > 200 ? "(first 200)" : `(${fills.length})`}</h3>
    <table>
      <thead><tr><th>Time (UTC)</th><th>Side</th><th>Type</th><th>Size</th><th>Price</th><th>Fee</th><th>Realised PnL</th><th>Equity</th></tr></thead>
      <tbody>${tradeRows}</tbody>
    </table>
  </div>

  <div class="foot">
    Reproducible run. Dataset SHA256 <code>${esc(man.datasetSha256.slice(0, 16))}…</code>,
    fee ${man.engine.feeBps} bps, slippage ${man.engine.slippageBps} bps, seed ${man.engine.seed}.
    Same inputs reproduce this scorecard byte for byte.
    Generated by bitget-agentbench ${esc(man.agentbenchVersion)}.
  </div>
</div>
</body>
</html>`;
}

const METRIC_ROWS: [string, (m: Scorecard["metrics"]) => string][] = [
  ["Max drawdown", (m) => cell("Max drawdown", fmtPct(-m.maxDrawdownPct))],
  ["Sharpe", (m) => cell("Sharpe", m.sharpe.toFixed(2))],
  ["Sortino", (m) => cell("Sortino", finite(m.sortino))],
  ["Win rate", (m) => cell("Win rate", fmtPct(m.winRatePct))],
  ["Profit factor", (m) => cell("Profit factor", finite(m.profitFactor))],
  ["Trades", (m) => cell("Trades", String(m.totalTrades))],
  ["Exposure", (m) => cell("Exposure", fmtPct(m.exposurePct))],
  ["Turnover", (m) => cell("Turnover", m.turnover.toFixed(2) + "x")],
  ["Total fees", (m) => cell("Total fees", fmt(m.totalFees))],
  ["Violations", (m) => cell("Violations", String(m.violations))],
];

function cell(k: string, v: string): string {
  return `<div class="metric"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`;
}

function tradeRow(f: Fill): string {
  const pnl = f.realizedPnl;
  const pnlCell = pnl === 0 ? "—" : `<span class="${pnl > 0 ? "pos" : "neg"}">${fmt(pnl)}</span>`;
  return `<tr>
    <td>${esc(isoUtc(f.time))}</td>
    <td class="${f.side}">${f.side}</td>
    <td>${f.orderType}</td>
    <td>${f.size}</td>
    <td>${fmt(f.price)}</td>
    <td>${f.fee.toFixed(2)}</td>
    <td>${pnlCell}</td>
    <td>${fmt(f.equityAfter)}</td>
  </tr>`;
}

/** Inline-SVG equity sparkline. */
function sparkline(equity: readonly number[], w: number, h: number): string {
  if (equity.length < 2) return `<div class="sub">No equity data.</div>`;
  const min = Math.min(...equity);
  const max = Math.max(...equity);
  const range = max - min || 1;
  const pad = 8;
  const pts = equity.map((e, i) => {
    const x = pad + (i / (equity.length - 1)) * (w - 2 * pad);
    const y = pad + (1 - (e - min) / range) * (h - 2 * pad);
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  });
  const start = equity[0]!;
  const end = equity[equity.length - 1]!;
  const stroke = end >= start ? "#3fb950" : "#f85149";
  // baseline at starting equity
  const baseY = pad + (1 - (start - min) / range) * (h - 2 * pad);
  return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="equity curve">
    <line x1="${pad}" y1="${baseY.toFixed(1)}" x2="${w - pad}" y2="${baseY.toFixed(1)}" stroke="#2a3340" stroke-dasharray="4 4" />
    <polyline fill="none" stroke="${stroke}" stroke-width="2" points="${pts.join(" ")}" />
  </svg>`;
}

// --- formatting helpers ---
function fmt(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
function fmtPct(n: number): string {
  return `${n >= 0 ? "+" : ""}${n.toFixed(2)}%`;
}
function finite(n: number | null): string {
  if (n === null) return "n/a";
  return Number.isFinite(n) ? n.toFixed(2) : "n/a";
}
function isoUtc(ts: number): string {
  return new Date(ts).toISOString().replace("T", " ").slice(0, 16);
}
function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!,
  );
}
